#!/bin/bash
#
# PHP CodeSniffer pre-commit hook for Git
#

# Get hook directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Use dependency of block-write.
. ${DIR}/src/block-write.sh

# Define the function that list all files to analyse depending on:
# - git command that list files
# - excluded folders
# - excluded files
. ${DIR}/src/get-file-list.sh

# Set the LIST of files to be parsed in the wanted scope.
get_file_list "git diff --name-only --cached --diff-filter=ACM"

. ${DIR}/src/hook-checker.sh

exit $?
